chore: properly configure ESLint on the backend folder

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -4,21 +4,35 @@
 echo '🏗️👷 Styling, testing and building your project before committing'
 
 # Check Prettier standards on frontend folder
-yarn frontend:lint ||
+yarn fe:lint ||
 (
     echo '🤢🤮🤢🤮 Prettier Check Failed. Run yarn format, add changes and try to commit again.';
     false;
 )
 
 # Check ESLint Standards on app folder
-yarn frontend:format ||
+yarn fe:format ||
 (
     echo '😤🏀👋😤 ESLint Check Failed. Make the required changes listed above and try to commit again.'
     false; 
 )
 
+# Format BE
+#yarn be:lint ||
+#(
+#    echo '🤢🤮🤢🤮 Prettier Check Failed. Run yarn format, add changes and try to commit again.';
+#    false; 
+#)
+
+# Format BE
+#yarn be:format ||
+#(
+#    echo '😤🏀👋😤 ESLint Check Failed. Make the required changes listed above and try to commit again.'
+#    false; 
+#)
+
 # Run BE tests
-yarn backend:e2e ||
+yarn be:e2e ||
 (
     echo "😤🏀👋😤 Test Failed, buggy code. I ain't going to commit this, the hell! - Try again."
     false; 
